[package]
name = "macros"
version = "0.1.0"
authors = ["Jan Adä <jan561.github@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
heck = "0.3"
